#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        id: 2
        gear_ratio: 1
        offset_position: 1900
        direction: 1
        max_effort: 0
        calibration_stall_threshold: 8

    stepper_2:
        id: 3
        gear_ratio: 1
        offset_position: 371
        direction: -1
        max_effort: 0
        calibration_stall_threshold: 8

    stepper_3:
        id: 4
        gear_ratio: 1
        offset_position: 855
        direction: 1
        max_effort: 0
        calibration_stall_threshold: 8
