calibration_timeout: 30
calibration_stall_threshold_motor_1: 6
calibration_stall_threshold_motor_2: 6
calibration_stall_threshold_motor_3: 6


calibration_file:  "/home/niryo/niryo_robot_saved_files/stepper_motor_calibration_offsets.txt"
