dynamixels:
    dxl_1:
        # assembly offset position (rad)
        offset_position: -3.1415
        # home position (rad)
        home_position: 0.0
        direction: 1
        # assembly direction (1 or -1)
        limit_position_max: 2.093
        limit_position_min: -2.093
        position_P_gain: 1024
        position_I_gain: 3642
        position_D_gain: 11200
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
        acceleration_profile: 0  # profile acc and vel used by dxl motors
        velocity_profile: 0

    dxl_2:
        offset_position: 3.1415
        home_position: 0.0
        direction: -1
        limit_position_max: 1.919
        limit_position_min: -1.919
        position_P_gain: 1024
        position_I_gain: 3642
        position_D_gain: 11200
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
        acceleration_profile: 0  # profile acc and vel used by dxl motors
        velocity_profile: 0

    dxl_3:
        offset_position: -3.1415
        home_position: 0.0
        direction: 1
        limit_position_max: 2.53
        limit_position_min: -2.53
        position_P_gain: 1024
        position_I_gain: 3642
        position_D_gain: 11200
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
        acceleration_profile: 0  # profile acc and vel used by dxl motors
        velocity_profile: 0
