dynamixels:
    dxl_1:
        offset_position: 0
        direction: 1
        position_P_gain: 5120
        position_I_gain: 500
        position_D_gain: 16383
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 400
        FF2_gain: 400

    dxl_2:
        offset_position: 0
        direction: -1
        position_P_gain: 3840
        position_I_gain: 500
        position_D_gain: 16383
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 400
        FF2_gain: 400

    dxl_3:
        offset_position: 0
        direction: 1
        position_P_gain: 5120
        position_I_gain: 3277
        position_D_gain: 7184
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 408