dynamixels:
    dxl_1:
        # assembly offset position (rad)
        offset_position: -3.1415
        # home position (rad)
        home_position: 0.0
        # assembly direction (1 or -1)
        direction: 1
        position_P_gain: 5120
        position_I_gain: 500
        position_D_gain: 16383
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 400
        FF2_gain: 400

    dxl_2:
        offset_position: 3.1415
        home_position: 0.0
        direction: -1
        position_P_gain: 3840
        position_I_gain: 500
        position_D_gain: 16383
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 400
        FF2_gain: 400

    dxl_3:
        offset_position: -3.1415
        home_position: 0.0
        direction: 1
        position_P_gain: 240
        position_I_gain: 66
        position_D_gain: 4800
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
