dynamixels:
    dxl_1:
        offset_position: 0
        direction: 1
        position_P_gain: 150
        position_I_gain: 20
        position_D_gain: 10
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0

    dxl_2:
        offset_position: 0
        direction: -1
        position_P_gain: 150
        position_I_gain: 20
        position_D_gain: 10
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0

    dxl_3:
        offset_position: 0
        direction: 1
        position_P_gain: 150
        position_I_gain: 20
        position_D_gain: 10
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
