#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        id: 2
        gear_ratio: 1
        offset_position: 1900
        direction: 1
        max_effort: 0
        v_start: 1
        a_1: 3600
        v_1: 4
        a_max: 4800
        v_max: 12
        d_max: 4800
        d_1: 3600
        v_stop: 2
        calibration_stall_threshold: 7

    stepper_2:
        id: 3
        gear_ratio: 1
        offset_position: 371
        direction: -1
        max_effort: 0
        v_start: 1
        a_1: 1300
        v_1: 4
        a_max: 1900
        v_max: 10
        d_max: 1900
        d_1: 1300
        v_stop: 2
        calibration_stall_threshold: 6
        
    stepper_3:
        id: 4
        gear_ratio: 1
        offset_position: 855
        direction: 1
        max_effort: 0
        v_start: 1
        a_1: 1800
        v_1: 4
        a_max: 2400
        v_max: 10
        d_max: 2400
        d_1: 1800
        v_stop: 2
        calibration_stall_threshold: 6
