#
#  Stepper caracteristics for Ned's hardware
#


# for profile, we need to reach the same velocities within the same times
# v_1-v_0 = a_1* dt
# v_max - v_1 = a_max * dt
# strategy : focus on stepper 2 and propagate
steppers:
    stepper_1:
        id: 2
        # gear_ratio, max_effort and micro_steps not used for ttl steppers
        motor_ratio: 0.0872
        # assembly offset position (rad)
        offset_position: -2.966
        # home position (rad)
        home_position: 0.0
        limit_position_min: -2.949  # joint limit min
        limit_position_max: 2.948   # joint limit max
        # assembly direction (1 or -1)
        direction: 1
        # rule is a_max = a_1 * 3
        #         d_max = d_1 * 3
        #         v_max = v_1 * 3
        #         d_max = a_max + 200
        v_start: 0
        a_1: 8000
        v_1: 1000
        a_max: 12000
        v_max: 4000
        d_max: 12000
        d_1: 8000
        v_stop: 100

    stepper_2:
        id: 3
        motor_ratio: 0.0868
        offset_position: 0.61
        home_position: 0.5
        limit_position_max: 0.61
        limit_position_min: -2.09
        direction: -1
        # rule is a_max = a_1 * 3
        #         d_max = d_1 * 3
        #         v_max = v_1 * 3
        #         d_max = a_max + 100
        v_start: 0
        a_1: 3440
        v_1: 600
        a_max: 5600
        v_max: 2000
        d_max: 5600
        d_1: 3440
        v_stop: 40
        
    stepper_3:
        id: 4
        motor_ratio: 0.0868
        offset_position: -1.34
        home_position: -1.25
        limit_position_min: -1.34
        limit_position_max: 1.57
        direction: 1
        # rule is a_max = a_1 * 3
        #         d_max = d_1 * 3
        #         v_max = v_1 * 3
        #         d_max = a_max + 100
        v_start: 0
        a_1: 4000
        v_1: 600
        a_max: 10000
        v_max: 3000
        d_max: 10000
        d_1: 4000
        v_stop: 40

