#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        id: 2
        # gear_ratio, max_effort and micro_steps not used for ttl steppers
        motor_ratio: 0.0872
        # assembly offset position (rad)
        offset_position: -2.96706
        # home position (rad)
        home_position: 0.0
        limit_position: 2.96706
        # assembly direction (1 or -1)
        direction: 1
        v_start: 1
        a_1: 1600
        v_1: 3
        a_max: 3200
        v_max: 14
        d_max: 3200
        d_1: 1600
        v_stop: 2

    stepper_2:
        id: 3
        motor_ratio: 0.0868
        offset_position: 0.610865
        home_position: 0.5
        limit_position: 0.610865
        direction: -1
        v_start: 1
        a_1: 1300
        v_1: 3
        a_max: 2500
        v_max: 12
        d_max: 2500
        d_1: 1300
        v_stop: 2
        
    stepper_3:
        id: 4
        motor_ratio: 0.0868
        offset_position: -1.3439
        home_position: -1.25
        limit_position: -1.3439
        direction: 1
        v_start: 1
        a_1: 1800
        v_1: 3
        a_max: 3000
        v_max: 12
        d_max: 3000
        d_1: 1800
        v_stop: 2

