#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        id: 2
        gear_ratio: 1
        offset_position: 1900
        direction: 1
        max_effort: 0
        v_start: 1
        a_1: 400
        v_1: 3
        a_max: 600
        v_max: 4
        d_max: 600
        d_1: 400
        v_stop: 2
        calibration_stall_threshold: 6

    stepper_2:
        id: 3
        gear_ratio: 1
        offset_position: 371
        direction: -1
        max_effort: 0
        v_start: 1
        a_1: 400
        v_1: 3
        a_max: 600
        v_max: 4
        d_max: 600
        d_1: 400
        v_stop: 2
        calibration_stall_threshold: 6
        
    stepper_3:
        id: 4
        gear_ratio: 1
        offset_position: 855
        direction: 1
        max_effort: 0
        v_start: 1
        a_1: 400
        v_1: 3
        a_max: 600
        v_max: 4
        d_max: 600
        d_1: 400
        v_stop: 2
        calibration_stall_threshold: 6
