#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        id: 2
        # gear_ratio, max_effort and micro_steps not used for ttl steppers
        motor_ratio: 0.0872
        # assembly offset position (rad)
        offset_position: -2.966
        # home position (rad)
        home_position: 0.0
        limit_position_min: -2.966  # joint limit min
        limit_position_max: 2.966   # joint limit max
        # assembly direction (1 or -1)
        direction: 1
        v_start: 1
        a_1: 1600
        v_1: 3
        a_max: 3200
        v_max: 14
        d_max: 3200
        d_1: 1600
        v_stop: 2

    stepper_2:
        id: 3
        motor_ratio: 0.0868
        offset_position: 0.61
        home_position: 0.5
        limit_position_max: 0.61
        limit_position_min: -2.09
        direction: -1
        v_start: 1
        a_1: 300
        v_1: 2
        a_max: 2500
        v_max: 12
        d_max: 2500
        d_1: 300
        v_stop: 2
        
    stepper_3:
        id: 4
        motor_ratio: 0.0868
        offset_position: -1.34
        home_position: -1.25
        limit_position_min: -1.34
        limit_position_max: 1.57
        direction: 1
        v_start: 1
        a_1: 1800
        v_1: 3
        a_max: 3000
        v_max: 12
        d_max: 3000
        d_1: 1800
        v_stop: 2

