variables:
  ROS_DISTRO: melodic
  ROS_LANG_DISABLE: genlisp:geneus:gennodejs
  SKIPPED_KEYS: python-rpi.gpio python-flask

stages:
  - build_n_test

catkin_make_n_rostest:
  only:
    refs:
      - master
      - develop
      - tags
      - schedules
      - merge_requests

  image: ros:${ROS_DISTRO}-ros-base-bionic
  stage: build_n_test
  script:
    # updating apt cache
    - apt-get update -y

    ## moving everything in src folder
    # Allow to use regex
    - shopt -s extglob
    # Create src folder
    - mkdir src
    # Move everything except src folder in src
    - mv !(src) src/

    # Installing Python
    - apt-get install -y python-dev python-pip

    # Installing package dependencies
    - rosdep update
    - rosdep install --from-paths src --ignore-src --default-yes --rosdistro $ROS_DISTRO --skip-keys "$SKIPPED_KEYS"

    # Test compiling
    - catkin_make

    # Test documentation build
    - catkin_make --cmake-args -DBUILD_DOCS=ON

    - source devel/setup.bash

    # C++ tests
    - catkin_make run_tests --cmake-args -DBUILD_UNIT_TESTS=ON -DBUILD_INTEGRATION_TESTS=ON

    # Python tests
    - python src/niryo_robot_unit_tests/scripts/script_test_headless.py

    # Check code linting
    - catkin_make roslint