variables:
  ROS_DISTRO: melodic
  ROS_LANG_DISABLE: genlisp:geneus:gennodejs
  SKIPPED_KEYS: python-rpi.gpio python-flask

stages:
  - build_n_test

catkin_make_n_rostest:
  only:
    refs:
      - master
      - develop
      - tags
      - schedules
      - merge_requests
      - web

  image: ros:${ROS_DISTRO}-ros-base-bionic
  stage: build_n_test
  artifacts:
    paths:
      - build
      - devel
      - src
  
  artifacts:
    when: always
    paths:
        - build/test_results/*/rostest-*.xml
        - build/test_results/*/gtest-*.xml
        - build/test_results/*/rosunit-*.xml
    reports:
      junit:
        - build/test_results/*/rostest-*.xml
        - build/test_results/*/gtest-*.xml
        - build/test_results/*/rosunit-*.xml

  script:
    # updating apt cache
    - apt-get update -y

    ## moving everything in src folder
    # Allow to use regex
    - shopt -s extglob
    # Create src folder
    - mkdir src
    # Move everything except src folder in src
    - mv !(src) src/

    # Installing Python
    - apt-get install -y python-dev python-pip

    # Installing package dependencies
    - rosdep update
    - rosdep install --from-paths src --ignore-src --default-yes --rosdistro $ROS_DISTRO --skip-keys "$SKIPPED_KEYS"

    # Compile project
    - catkin_make

    - source devel/setup.bash

    # Launch roscore in background
    - roscore&

    # Launch all tests (python / C++)
    # Note: Without -j1, multiple jobs was running and problems occured for xml results output files
    # (sometimes a part of file was duplicated and unreadable by scripts then)
    - catkin_make run_tests -j1

    # Check code linting
    - catkin_make roslint

    # Check config files (package.xml + CMakeLists.txt)
    - catkin_lint -W2 --rosdistro melodic --ignore missing_directory --explain src --show-ignored