# Important note:
# All the values finishing with "_hold_torque" have been computed so the
# DXL-320 motor won't become too hot.
# If you increase those values you may destroy (burn) the motor after a few minutes.

tool_list:
  - name: "No Tool"
    type: "no_tool"
    id: 0
    specs:
      [ ]
    available_commands:
      [ ]
    transformation:
      translation: [0.0, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]
  - name: "Gripper 1"
    type: "gripper"
    id: 11
    available_commands:
      - open_gripper
      - close_gripper
    specs:
      open_position: 1470
      open_hold_torque: 500
      open_max_torque: 1023
      close_position: 370
      close_hold_torque: 65000
      close_max_torque: 64000
      open_speed: 300
      close_speed: 300
      limit_open_speed:
        min: 0
        max: 1023
      limit_close_speed:
        min: 0
        max: 1023
    transformation:
      translation: [0.085, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]
  - name: "Gripper 2"
    type: "gripper"
    id: 12
    available_commands:
      - open_gripper
      - close_gripper
    specs:
      open_position: 2380
      open_hold_torque: 500
      open_max_torque: 1023
      close_position: 1580
      close_hold_torque: 65000
      close_max_torque: 64000
      open_speed: 300
      close_speed: 300
      limit_open_speed:
        min: 0
        max: 1023
      limit_close_speed:
        min: 0
        max: 1023
    transformation:
      translation: [0.113, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]
  - name: "Gripper 3"
    type: "gripper"
    id: 13
    available_commands:
      - open_gripper
      - close_gripper
    specs:
      open_position: 1980
      open_hold_torque: 500
      open_max_torque: 1023
      close_position: 970
      close_hold_torque: 65000
      close_max_torque: 64000
      open_speed: 300
      close_speed: 300
      limit_open_speed:
        min: 0
        max: 1023
      limit_close_speed:
        min: 0
        max: 1023
    transformation:
      translation: [0.1215, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]
  - name: "Gripper 4"
    type: "gripper"
    id: 14
    available_commands:
      - open_gripper
      - close_gripper
    specs:
      open_position: 518
      open_hold_torque: 500
      open_max_torque: 1023
      close_position: 157
      close_hold_torque: 65000
      close_max_torque: 64000
      open_speed: 300
      close_speed: 300
      limit_open_speed:
        min: 0
        max: 1023
      limit_close_speed:
        min: 0
        max: 1023
    transformation:
      translation: [0.1215, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]
  - name: "Electromagnet 1"
    type: "electromagnet"
    id: 30
    available_commands:
      - activate_digital_io
      - deactivate_digital_io
      - setup_digital_io
    specs:
      [ ]
    transformation:
      translation: [0.0225, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]
  - name: "Vacuum Pump 1"
    type: "vacuum_pump"
    id: 31
    available_commands:
      - pull_air_vacuum_pump
      - push_air_vacuum_pump
    specs:
      pull_air_velocity: 1023
      pull_air_position: 250
      pull_air_max_torque: 500
      pull_air_hold_torque: 128
      push_air_velocity: 1023
      push_air_position: 760
      push_air_max_torque: 64000
    transformation:
      translation: [0.047, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]


