joint_1_name: "joint_1"
joint_2_name: "joint_2"
joint_3_name: "joint_3"
joint_4_name: "joint_4"
joint_5_name: "joint_5"
joint_6_name: "joint_6"

joint_1_protocol: "ttl"
joint_2_protocol: "ttl"
joint_3_protocol: "ttl"
joint_4_protocol: "ttl"
joint_5_protocol: "ttl"
joint_6_protocol: "ttl"