# fake params using in fake driver
fake_params:
    id_list: [2, 3, 4, 5, 6, 7, 8, 11, 0]
    steppers:
        id: [2, 3, 4, 8]
        position: [1950, 0, 0, 0]
        velocity: [0, 0, 0, 0]
        temperature: [50, 52, 54, 55]
        # these are raw parameters, as they should appear on the bus
        voltage: [12100, 12200, 12300, 12000]
        min_position: [0, 0, 0, 0]
        max_position: [4096, 4096, 4096, 4096]
        model_number: [1, 1, 1, 2]
        firmware: ["0.0.1", "0.0.1", "0.0.1", "0.0.1"]
    dynamixels:
        id: [5, 6, 7, 11]
        position: [2048, 2048, 2048, 370]
        velocity: [0, 0, 0, 0]
        temperature: [50, 52, 54, 56]
        # these are raw parameters, as they should appear on the bus
        voltage: [50, 50, 50, 50]
        min_position: [0, 0, 0, 0]
        max_position: [4096, 4096, 4096, 4096]
        model_number: [1, 1, 1, 1]
        firmware: ["0.0.1", "0.0.1", "0.0.1", "0.0.1"]
    end_effector:
        id: 0
        temperature: 32
        voltage: 5000
        firmware: "0.0.1"
