#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        id: 2
        gear_ratio: 1
        offset_position: 1900
        home_position: 0.0
        direction: 1
        max_effort: 0

    stepper_2:
        id: 3
        gear_ratio: 1
        offset_position: 371
        home_position: 0.5
        direction: -1
        max_effort: 0
        
    stepper_3:
        id: 4
        gear_ratio: 1
        offset_position: 855
        home_position: -1.25
        direction: 1
        max_effort: 0
