publish_io_state_frequency: 10
check_interrupt_flag_security_frequency: 4

button:
  gpio: 4

mcp:
 address: 32
 num_gpios: 16
 i2c_bus: 0
 interrupt_bcm: 26

adc:
  i2c_bus: 0
  address: 54
  v_ref: 3.0
  resolution: 12

fans:
  - pin: 8
    temperature_on_threshold: 45
    temperature_off_threshold: 40
  - pin: 9
    temperature_on_threshold: 55
    temperature_off_threshold: 50

wifi:
  led_pin: 4
  button_pin: 5

end_effector_ios:
   digital_input: DI4
   digital_output: DO4

shutdown_manager:
  digital_input: 13
  digital_output:
    pin: 7
    reverse: False

digital_inputs:
  - name: DI1
    pin: 0
  - name: DI2
    pin: 1
  - name: DI3
    pin: 2
  - name: DI5
    pin: 3

digital_outputs:
  - name: DO1
    pin: 12
    reverse: True
  - name: DO2
    pin: 11
    reverse: True
  - name: DO3
    pin: 10
    reverse: True

analog_outputs:
  - name: AO1
    pin: 0
    address: 73
    i2c_bus: 0
    v_ref: 5.0
    resolution: 12
  - name: AO2
    pin: 0
    address: 75
    i2c_bus: 0
    v_ref: 5.0
    resolution: 12

analog_inputs:
  - name: AI1
    pin: 0
  - name: AI2
    pin: 1
