# not used actually
#
#  Stepper caracteristics for Ned's hardware
#
#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        id: 1
        gear_ratio: 5.4375
        offset_position: 2.96706
        home_position: 0.0
        direction: -1
        max_effort: 110

    stepper_2:
        id: 2
        gear_ratio: 8.5625
        offset_position: 0.610865
        home_position: 0.5
        direction: -1
        max_effort: 130
        
    stepper_3:
        id: 3
        gear_ratio: 7.6875
        offset_position: -1.3439
        home_position: -1.25
        direction: -1
        max_effort: 120

dynamixels:
    dxl_1:
        offset_position: 0
        direction: 1
        position_P_gain: 640
        position_I_gain: 500
        position_D_gain: 1000
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0

    dxl_2:
        offset_position: 0
        direction: -1
        position_P_gain: 640
        position_I_gain: 500
        position_D_gain: 1000
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0

    dxl_3:
        direction: 1
        offset_position: 0
        position_P_gain: 84
        position_I_gain: 9
        position_D_gain: 5