dynamixels:
    dxl_1:
        offset_position: 0
        direction: 1
        position_P_gain: 640
        position_I_gain: 500
        position_D_gain: 1000
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0

    dxl_2:
        offset_position: 0
        direction: -1
        position_P_gain: 640
        position_I_gain: 500
        position_D_gain: 1000
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0

    dxl_3:
        offset_position: 0
        direction: 1
        position_P_gain: 84
        position_I_gain: 9
        position_D_gain: 5
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0