#
#  Stepper caracteristics for Ned 2 hardware
#
steppersTtl:
    stepper_1:
        id: 2
        gear_ratio: 1
        offset_position: 1900
        home_position: 0
        direction: 1
        max_effort: 0

    stepper_2:
        id: 3
        gear_ratio: 1
        offset_position: 1350
        home_position: 0
        direction: 1
        max_effort: 0
        
    stepper_3:
        id: 4
        gear_ratio: 1
        offset_position: 872
        home_position: 0
        direction: 1
        max_effort: 0




