blacklist: []
build_space: build/debug
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Debug
- -DHARWARE_VERSION=ned2
devel_layout: linked
devel_space: devel/debug
extend_path: null
install: true
install_space: install/debug
isolate_install: false
jobs_args: []
log_space: log/debug
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
