#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        id: 1
        gear_ratio: 6.0625
        offset_position: 3.05433
        direction: -1
        max_effort: 90

    stepper_2:
        id: 2
        gear_ratio: 8.3125
        offset_position: 0.640187
        direction: -1
        max_effort: 130
        
    stepper_3:
        id: 3
        gear_ratio: 7.875
        offset_position: -1.397485
        direction: 1
        max_effort: 120
