ttl_hardware_control_loop_frequency: 500.0
ttl_hardware_write_frequency: 100.0
ttl_hardware_read_data_frequency: 80.0
ttl_hardware_read_end_effector_frequency: 10.0
ttl_hardware_read_status_frequency: 0.5
